In [1]:
import pandas as pd
import yaml

# Monge DrugDose OOD

In [2]:
drugs = ["abexinostat", "belinostat", "dacinostat", "entinostat", "givinostat", 
             "mocetinostat", "pracinostat", "tacedinaline", "trametinib"]
exp_order = ["homogenous_valid_set"]+ ["Monge-ood", "Identity", "within_condition"] * 4
dosages=["-10", "-100", "-1000", "-10000"]

all_mean_metrics = []
for drug in drugs:

    with open(f"/Users/adr/Box/otperturb/alice_exp/sciplex_monge_ood/{drug}/logs.yaml") as stream:
        logs = yaml.safe_load(stream)

    print(drug, len(logs["experiments"]))
    for i, d in enumerate(logs["experiments"]):
        if i==0:
            continue
            
        mean_stats = d["mean_statistics"]
        mean_stats = pd.DataFrame.from_dict(mean_stats, orient="index").T
        mean_stats["eval_setting"] = exp_order[i]
        mean_stats["ood_drug"] = drug
        mean_stats["model"] = "Monge-ood"
        mean_stats["condition"] = drug+dosages[(i-1)%4]
        all_mean_metrics.append(mean_stats)

abexinostat 13
belinostat 13
dacinostat 13
entinostat 13
givinostat 13
mocetinostat 13
pracinostat 13
tacedinaline 13
trametinib 13

In [3]:
ood_res = pd.concat(all_mean_metrics)
ood_res[["drug", "dose"]] = [c.split("-") for c in ood_res["condition"]]
ood_res = ood_res[ood_res["eval_setting"]=="Monge-ood"].reset_index(drop=True)

In [4]:
ood_res.groupby(["dose"]).mean(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,3.880775,0.017997,3.314196,13.435410,1.313935,0.715236
100,6.260023,0.105065,5.710327,12.955359,4.265607,0.237694
1000,4.230843,0.026320,3.670650,13.347229,1.725676,0.610503
10000,3.939706,0.020570,3.375325,13.414275,1.380290,0.663256

In [5]:
ood_res.groupby(["dose"]).std(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,0.913271,0.005717,0.913253,0.359349,0.560708,0.164656
100,1.681540,0.080124,1.682757,0.402571,2.407279,0.293681
1000,1.044799,0.027966,1.045274,0.448246,1.114845,0.287682
10000,0.850227,0.009833,0.848764,0.392245,0.537175,0.249239

# Monge DrugDose ID

In [6]:
with open(f"/Users/adr/Box/otperturb/alice_exp/sciplex_monge_id/one_model_monge_sciplex_logs.yml") as stream:
        logs = yaml.safe_load(stream)

with open(f"/Users/adr/Box/otperturb/alice_exp/sciplex_monge_id/monge-one-model-ID-sciplex.yml") as stream:
        config = yaml.safe_load(stream)

In [7]:
conditions = [c for c in config["drug_conditions"] for i in range(2)]
conditions

['abexinostat-10',
 'abexinostat-10',
 'abexinostat-100',
 'abexinostat-100',
 'abexinostat-1000',
 'abexinostat-1000',
 'abexinostat-10000',
 'abexinostat-10000',
 'belinostat-10',
 'belinostat-10',
 'belinostat-100',
 'belinostat-100',
 'belinostat-1000',
 'belinostat-1000',
 'belinostat-10000',
 'belinostat-10000',
 'dacinostat-10',
 'dacinostat-10',
 'dacinostat-100',
 'dacinostat-100',
 'dacinostat-1000',
 'dacinostat-1000',
 'dacinostat-10000',
 'dacinostat-10000',
 'entinostat-10',
 'entinostat-10',
 'entinostat-100',
 'entinostat-100',
 'entinostat-1000',
 'entinostat-1000',
 'entinostat-10000',
 'entinostat-10000',
 'givinostat-10',
 'givinostat-10',
 'givinostat-100',
 'givinostat-100',
 'givinostat-1000',
 'givinostat-1000',
 'givinostat-10000',
 'givinostat-10000',
 'mocetinostat-10',
 'mocetinostat-10',
 'mocetinostat-100',
 'mocetinostat-100',
 'mocetinostat-1000',
 'mocetinostat-1000',
 'mocetinostat-10000',
 'mocetinostat-10000',
 'pracinostat-10',
 'pracinostat-10',
 'pracinostat-100',
 'pracinostat-100',
 'pracinostat-1000',
 'pracinostat-1000',
 'pracinostat-10000',
 'pracinostat-10000',
 'tacedinaline-10',
 'tacedinaline-10',
 'tacedinaline-100',
 'tacedinaline-100',
 'tacedinaline-1000',
 'tacedinaline-1000',
 'tacedinaline-10000',
 'tacedinaline-10000',
 'trametinib-10',
 'trametinib-10',
 'trametinib-100',
 'trametinib-100',
 'trametinib-1000',
 'trametinib-1000',
 'trametinib-10000',
 'trametinib-10000']

In [8]:
id_res = [pd.DataFrame(logs["experiments"][i]["mean_statistics"], index=[conditions[i]]) for i in range(len(logs["experiments"]))]
id_res = pd.concat(id_res)
id_res[["drug", "dose"]] = [i.split("-") for i in id_res.index]
id_res = id_res.reset_index(drop=False).rename(columns={"index": "condition"})
id_res["eval_setting"] = ["Monge-id", "identity"]*36
id_res = id_res[id_res["eval_setting"]=="Monge-id"].reset_index(drop=True)
id_res

,condition,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2,drug,dose,eval_setting
0,abexinostat-10,3.242397,0.012849,2.665836,13.152071,0.962576,0.670340,abexinostat,10,Monge-id
1,abexinostat-100,3.340483,0.018145,2.768108,13.086434,1.106684,0.599862,abexinostat,100,Monge-id
2,abexinostat-1000,3.397719,0.023527,2.832800,13.074697,1.176057,0.549883,abexinostat,1000,Monge-id
3,abexinostat-10000,5.895378,0.107262,5.335856,12.851451,4.493033,0.074325,abexinostat,10000,Monge-id
4,belinostat-10,4.402564,0.015837,3.824017,13.495016,1.678830,0.641696,belinostat,10,Monge-id
5,belinostat-100,4.137097,0.011902,3.559520,13.466353,1.346611,0.686163,belinostat,100,Monge-id
6,belinostat-1000,4.214706,0.012943,3.644569,13.427165,1.365426,0.725358,belinostat,1000,Monge-id
7,belinostat-10000,5.874518,0.074624,5.321491,13.066709,3.949614,0.036815,belinostat,10000,Monge-id
8,dacinostat-10,3.230243,0.016642,2.657682,12.942149,0.921227,0.763139,dacinostat,10,Monge-id
9,dacinostat-100,3.346111,0.028279,2.784163,12.931560,0.995622,0.644661,dacinostat,100,Monge-id
10,dacinostat-1000,5.269732,0.070601,4.714922,12.985080,3.578982,0.103724,dacinostat,1000,Monge-id
11,dacinostat-10000,7.981266,0.195277,7.431277,12.724925,6.850047,0.045130,dacinostat,10000,Monge-id
12,entinostat-10,3.705299,0.011699,3.139519,13.389245,1.020332,0.809068,entinostat,10,Monge-id
13,entinostat-100,3.771920,0.013425,3.202592,13.349663,1.146048,0.801661,entinostat,100,Monge-id
14,entinostat-1000,3.738168,0.011234,3.176108,13.514256,0.891380,0.838346,entinostat,1000,Monge-id
15,entinostat-10000,4.544844,0.032775,3.989393,13.117665,1.945848,0.654072,entinostat,10000,Monge-id
16,givinostat-10,3.797018,0.019301,3.227227,13.443545,1.369888,0.827629,givinostat,10,Monge-id
17,givinostat-100,3.742074,0.018882,3.176301,13.528293,1.270091,0.853801,givinostat,100,Monge-id
18,givinostat-1000,3.710239,0.018713,3.157540,13.503051,1.253017,0.867935,givinostat,1000,Monge-id
19,givinostat-10000,7.529104,0.146149,6.981412,12.899121,6.156896,0.009033,givinostat,10000,Monge-id
20,mocetinostat-10,5.366186,0.016914,4.791839,14.094075,1.891872,0.845705,mocetinostat,10,Monge-id
21,mocetinostat-100,4.996535,0.012290,4.419035,14.117193,1.582138,0.859995,mocetinostat,100,Monge-id
22,mocetinostat-1000,5.006878,0.012375,4.432557,14.093996,1.603022,0.858773,mocetinostat,1000,Monge-id
23,mocetinostat-10000,5.226441,0.028106,4.686277,13.449018,1.847413,0.508337,mocetinostat,10000,Monge-id
24,pracinostat-10,2.984309,0.012099,2.408894,13.082381,0.951347,0.678623,pracinostat,10,Monge-id
25,pracinostat-100,3.007706,0.013312,2.436958,13.045427,0.935663,0.687928,pracinostat,100,Monge-id
26,pracinostat-1000,3.056802,0.017446,2.489005,13.042242,0.917030,0.724066,pracinostat,1000,Monge-id
27,pracinostat-10000,7.373322,0.192314,6.819174,12.690013,6.356086,0.065014,pracinostat,10000,Monge-id
28,tacedinaline-10,4.553331,0.013069,3.982359,14.037179,1.271660,0.795736,tacedinaline,10,Monge-id
29,tacedinaline-100,4.600611,0.012564,4.036988,13.905034,1.257473,0.807461,tacedinaline,100,Monge-id
30,tacedinaline-1000,4.472397,0.011209,3.907226,14.073082,1.089297,0.820253,tacedinaline,1000,Monge-id
31,tacedinaline-10000,4.582432,0.012784,4.017681,14.010088,1.197833,0.858336,tacedinaline,10000,Monge-id
32,trametinib-10,4.191624,0.027262,3.634289,13.134506,2.014864,0.257716,trametinib,10,Monge-id
33,trametinib-100,3.938137,0.021873,3.381411,13.260264,1.632474,0.466518,trametinib,100,Monge-id
34,trametinib-1000,3.946909,0.022101,3.384865,13.178014,1.700969,0.440332,trametinib,1000,Monge-id
35,trametinib-10000,4.041347,0.026056,3.490034,13.186623,1.805950,0.375465,trametinib,10000,Monge-id

In [9]:
id_res.groupby(["dose"]).mean(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,3.941441,0.016186,3.370185,13.418908,1.342511,0.698850
100,3.875630,0.016742,3.307231,13.410025,1.252534,0.712006
1000,4.090394,0.022239,3.526621,13.432398,1.508353,0.658741
10000,5.894295,0.090594,5.341400,13.110624,3.844746,0.291836

In [10]:
id_res.groupby(["dose"]).std(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,0.763767,0.004885,0.764286,0.408966,0.425937,0.181282
100,0.632748,0.005584,0.631222,0.396063,0.240104,0.131235
1000,0.727104,0.018716,0.727045,0.419059,0.824283,0.254563
10000,1.442108,0.072794,1.443882,0.413655,2.232543,0.318324

# Monge Dose OOD

In [11]:
drugs = ["abexinostat", "belinostat", "dacinostat", "entinostat", "givinostat", 
             "mocetinostat", "pracinostat", "tacedinaline", "trametinib"]
exp_order = ["homogenous_valid_set"]+ ["Monge-ood", "Identity", "within_condition"]
dosages=["-10", "-100", "-1000", "-10000"]

all_mean_metrics = []
for drug in drugs:
    for dose in dosages:

        with open(f"/Users/adr/Box/otperturb/alice_exp/sciplex_monge_dose_ood/{drug}{dose}/logs.yaml") as stream:
            logs = yaml.safe_load(stream)
    
        print(drug, len(logs["experiments"]))
        for i, d in enumerate(logs["experiments"]):
        
            mean_stats = d["mean_statistics"]
            mean_stats = pd.DataFrame.from_dict(mean_stats, orient="index").T
            mean_stats["eval_setting"] = exp_order[i]
            mean_stats["ood_drug"] = f"{drug}{dose}"
            mean_stats["model"] = "Monge-ood"
            mean_stats["drug"] = drug
            mean_stats["dose"] = dose[1:]
            all_mean_metrics.append(mean_stats)

abexinostat 4
abexinostat 4
abexinostat 4
abexinostat 4
belinostat 4
belinostat 4
belinostat 4
belinostat 4
dacinostat 4
dacinostat 4
dacinostat 4
dacinostat 4
entinostat 4
entinostat 4
entinostat 4
entinostat 4
givinostat 4
givinostat 4
givinostat 4
givinostat 4
mocetinostat 4
mocetinostat 4
mocetinostat 4
mocetinostat 4
pracinostat 4
pracinostat 4
pracinostat 4
pracinostat 4
tacedinaline 4
tacedinaline 4
tacedinaline 4
tacedinaline 4
trametinib 4
trametinib 4
trametinib 4
trametinib 4

In [12]:
dose_ood = pd.concat(all_mean_metrics).reset_index(drop=True)

In [13]:
dose_ood = dose_ood[dose_ood["eval_setting"]=="Monge-ood"].reset_index(drop=True)
dose_ood.groupby("dose").mean(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,4.074573,0.023590,3.507992,13.311979,1.467953,0.613687
100,3.868805,0.019281,3.304423,13.350407,1.217974,0.726488
1000,3.774746,0.015575,3.214555,13.379097,0.984428,0.856421
10000,6.130077,0.103564,5.580383,12.922187,4.132846,0.321623

In [14]:
dose_ood.groupby("dose").std(numeric_only=True)

,mean_wasserstein,mean_mmd,mean_sinkhorn div,mean_monge_gap,mean_drug_signature,mean_r2
dose,,,,,,
10,0.761364,0.018237,0.758160,0.436610,0.817823,0.349241
100,0.681003,0.008844,0.677106,0.383812,0.435965,0.218906
1000,0.725690,0.013310,0.723493,0.391801,0.683793,0.111791
10000,1.587656,0.075008,1.589381,0.358049,2.355036,0.348387